spring:
  application:
    name: subscription-api
  datasource:
    url: jdbc:mysql://localhost:3307/subscription_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Stockholm
    username: root
    password: root
    hikari:
      pool-name: HikariJpaPool
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQLDialect

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha
  api-docs:
    path: /v3/api-docs

app:
  jwt:
    secret: "V2VyeUxpbm9fUmFuZG9tX1NlY3JldF9LZXlfRm9yX1N1YnNjcmlwdGlvbl9BcGlfQXBwbGljYXRpb25fR2VuZXJhdGVkX0J5X01lX0Zvcl9TZWN1cml0eQ=="
    expiration-ms: 86400000
  security:
    token-blacklist:
      enabled: true
